analytics/zero-etl-integrations/rds-mysql-to-redshift/.gitignore

add .gitignore

---

machine-learning/sagemaker/deepseek-on-sagemaker/deepseek-r1-distill-qwen-32b/src/notebook/deepseek_r1_32b_realtime_endpoint.ipynb

fix errors - update SageMaker version

---

analytics/cdc-data-pipeline/aws-dms/aws-dms-cdc-data-pipeline/utils/gen_fake_mysql_data.py
analytics/cdc-data-pipeline/aws-dms/aws-dms-serverless-mysql-to-s3-migration/utils/gen_fake_mysql_data.py
analytics/cdc-data-pipeline/aws-dms/aws-dms-serverless-to-kinesis-data-pipeline/utils/gen_fake_mysql_data.py
analytics/cdc-data-pipeline/aws-msk-debezium/aws-msk-cdc-data-pipeline-with-debezium/utils/gen_fake_mysql_data.py
analytics/cdc-data-pipeline/aws-msk-debezium/aws-msk-serverless-cdc-data-pipeline-with-debezium/utils/gen_fake_mysql_data.py
analytics/transactional-datalake/transactional-datalake-using-amazon-datafirehose-and-apache-iceberg/src/utils/gen_fake_mysql_data.py
analytics/transactional-datalake/transactional-datalake-using-amazon-msk-and-apache-iceberg-on-aws-glue/src/utils/gen_fake_mysql_data.py
analytics/transactional-datalake/transactional-datalake-using-amazon-msk-serverless-and-apache-iceberg-on-aws-glue/src/utils/gen_fake_mysql_data.py
analytics/transactional-datalake/transactional-datalake-using-apache-iceberg-on-aws-glue/src/utils/gen_fake_mysql_data.py

fix SQL errors

---

machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-async-inference/src/python/code/inference.py
machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-realtime-inference/src/python/code/inference.py

update transformer version

---

machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-async-inference/cdk_stacks/sm_llava_next_video_async_endpoint.py
machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-realtime-inference/cdk_stacks/sm_llava_next_video_realtime_endpoint.py

update default Deep Learning Container for LlaVA-Next-Video

---

machine-learning/sagemaker/deepseek-on-sagemaker/janus-pro-7b/.example.cdk.context.json
machine-learning/sagemaker/deepseek-on-sagemaker/janus-pro-7b/README.md
machine-learning/sagemaker/deepseek-on-sagemaker/janus-pro-7b/cdk_stacks/sm_janus_pro_realtime_endpoint.py
machine-learning/sagemaker/deepseek-on-sagemaker/janus-pro-7b/requirements.txt

use HuggingFace DLC instead of PyTorch DLC

---

machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-realtime-inference/src/notebook/deploy_llava_next_video_on_sagemaker_realtime_endpoint.ipynb

update deploy notebook

---

machine-learning/sagemaker/deepseek-on-sagemaker/janus-pro-7b/README.md
machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-realtime-inference/README.md

refactor README.md files

---

machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-realtime-inference/src/notebook/deploy_llava_next_video_on_sagemaker_realtime_endpoint.ipynb
machine-learning/sagemaker/video-llava-on-aws-sagemaker/src/notebook/deploy_video_llava_on_sagemaker_realtime_endpoint.ipynb

refactor codes to get image_uri from region

---

machine-learning/sagemaker/deepseek-on-sagemaker/deepseek-r1-distill-qwen-14b/src/python/code/serving.properties

fix the wrong model_id in serving.perperties file

---

machine-learning/sagemaker/deepseek-on-sagemaker/deepseek-r1-distill-qwen-14b/src/python/code/model.py
machine-learning/sagemaker/deepseek-on-sagemaker/deepseek-v2-lite-chat/src/python/code/model.py

refactor model.py (custom inference script)

---

machine-learning/sagemaker/deepseek-on-sagemaker/deepseek-r1-llama-8b-sglang/README.md

update References in README.md

---

machine-learning/sagemaker/deepseek-on-sagemaker/deepseek-r1-llama-8b-sglang/README.md
machine-learning/sagemaker/deepseek-on-sagemaker/deepseek-r1-llama-8b-sglang/requirements.txt

upgrade cdk-ecr-deployment version upto v4.0.1

---

analytics/transactional-datalake/transactional-datalake-using-amazon-datafirehose-and-apache-iceberg/cdk_stacks/firehose_to_iceberg.py

refactor codes

---

machine-learning/sagemaker/deepseek-on-sagemaker/deepseek-r1-distill-llama-8b-sglang/src/container/serve
machine-learning/sagemaker/lgai-exaone-on-sagemaker/exaone-deep-7_8b-sglang/src/container/serve

fix errors in SGLang serve scripts

---

machine-learning/sagemaker/qwen-vl-on-sagemaker-endpoint/qwen2_5-vl-32b-sglang/README.md

fix typoes

---

machine-learning/sagemaker/qwen-vl-on-sagemaker-endpoint/qwen2_5-vl-32b-sglang/src/notebook/deploy_qwen25_vl_32b_sglang.ipynb
machine-learning/sagemaker/qwen-vl-on-sagemaker-endpoint/qwen2_5-vl-32b-sglang/src/notebook/qwen25_vl_32b_sglang_realtime_endpoint.ipynb

fix typoes in notebook

---

analytics/streaming-data-to-s3tables-with-datafirehose/README.md
analytics/streaming-data-to-s3tables-with-datafirehose/app.py
analytics/streaming-data-to-s3tables-with-datafirehose/cdk_stacks/__init__.py
analytics/streaming-data-to-s3tables-with-datafirehose/cdk_stacks/lake_formation.py
analytics/streaming-data-to-s3tables-with-datafirehose/requirements.txt

add DataLakePermissions cdk stack

---

analytics/streaming-data-to-s3tables-with-datafirehose/README.md

refactor the style in README.md

---

analytics/streaming-data-to-s3tables-with-datafirehose/README.md

update References section in README.md

---

machine-learning/sagemaker/deepseek-on-sagemaker/janus-pro-7b/README.md
machine-learning/sagemaker/lgai-exaone-on-sagemaker/exaone-deep-7_8b-sglang/README.md
machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-async-inference/README.md
machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-realtime-inference/README.md
machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-async-inference/pytorch/README.md
machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-realtime-inference/pytorch/README.md

fix tar command errors to create model.tar.gz

---

gen-ai/mcp-tutorial/module-01/README.md

Fix Readme

---

machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-async-inference/hugging-face/src/notebook/async-hugging-face.ipynb
machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-realtime-inference/hugging-face/src/notebook/realtime-hugging-face.ipynb

… model test
*Issue #, if available:* None
*Description of changes:* Fix: parameter missing error while downloading audio file for whisper test

Fix: parameter missing error while downloading audio file for whisper test

---

machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-async-inference/hugging-face/src/notebook/async-hugging-face.ipynb
machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-async-inference/jumpstart/src/notebook/async-jumpstart.ipynb
machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-async-inference/pytorch/src/notebook/async-pytorch.ipynb
machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-realtime-inference/hugging-face/src/notebook/realtime-hugging-face.ipynb
machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-realtime-inference/jumpstart/src/notebook/realtime-jumpstart.ipynb
machine-learning/sagemaker/whisper-model-hosting-on-sagemaker-endpoint/sagemaker-realtime-inference/pytorch/src/notebook/realtime-pytorch.ipynb

refactor notebooks

---

gen-ai/mcp-tutorial/module-01/part-01/README.md

Fix readme image

---

machine-learning/sagemaker/llava-next-video-model-on-sagemaker-endpoint/sagemaker-async-inference/src/python/code/requirements.txt
machine-learning/sagemaker/video-llava-on-aws-sagemaker/src/python/code/requirements.txt

update transformers version to enhance security

---

gen-ai/mcp-tutorial/README.md

fix broken links

---

gen-ai/mcp-tutorial/README.ko.md

update the list of Modules

---

machine-learning/sagemaker/qwen3-embedding/src/notebook/deploy_qwen3_embedding_06b_on_sagemaker_endpoint.ipynb

fix typo in model name

---

machine-learning/sagemaker/qwen3-embedding/src/notebook/deploy_qwen3_embedding_06b_on_sagemaker_endpoint.ipynb

fix typo in qwen embedding deployment
